name: mvpipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - tqdm
  - pyyaml
  - spglib
  - pymatgen
  - matminer
  - streamlit
  - py3Dmol
  - pip:
      - typer
      - rich
